# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               La Communication Animale
tagline:             Que permettent les nouvelles connaissances en matière de communication animale ?
url:                 https://communicationanimale.tk
paginate:            1
baseurl:             "/CommunicationAnimale2/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              
  url:               
  email:             

# Site
theme :
  footer_text: >
   Créé par des élèves du <a href="http://www.lycee-delacroix-maisons-alfort.fr/">Lycée Delacroix</a>
   <br>2015

# Collections
collections:
  tpe:
    output: true
    permalink: /:collection/:title/

# Build
markdown: kramdown
kramdown:
   math_engine: mathjax
